author = "Claudiu Tănăselia"
baseurl = "/"
canonifyurls = true
languageCode = "ro"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
theme = "alageek"
title = "parsec.ro"

[params]
copyright = "©2009-2019 parsec.ro | un site de Claudiu Tănăselia."
copyrightUrl = "https://www.parsec.ro"
faviconfile = "/blog/i/favicon.ico"
latestpostcount = 5
logofile = "/blog/i/logo.png"
highlightjs = false

[[params.best_posts]]
title = "Lansări orbitale în 2019"
url = "/blog/lansari2019/"

[[params.best_posts]]
title = "Sonde interplanetare"
url = "/blog/sonde/"

[[params.best_posts]]
title = "Stația Spațială Internațională"
url = "/blog/iss/"

[[menu.primary]]
identifier = "blog"
name = "Buletin cosmic"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "FAQ"
name = "FAQ"
url = "/faq/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "Despre site"
url = "/about/"
weight = 30

[[menu.secondary]]
identifier = "patreon"
name = "Donează prin Patreon"
url = "https://www.patreon.com/bePatron?u=10637849"
weight = 110

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
