author = "Claudiu Tănăselia"
baseurl = "/"
canonifyurls = true
languageCode = "ro"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
theme = "alageek"
title = "parsec.ro"

[params]
copyright = "©2009-2019 parsec.ro | un site de Claudiu Tănăselia"
copyrightUrl = "https://www.parsec.ro"
faviconfile = "https://gokmengorgen.net/img/laughing-man-favicon.png"
latestpostcount = 5
logofile = "https://i.imgur.com/GVtzkol.png"
highlightjs = false

[[params.best_posts]]
title = "Migrate to Hugo from Jekyll"
url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Buletin cosmic"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "Despre site"
url = "/about/"
weight = 20

[[menu.secondary]]
identifier = "patreon"
name = "Susține pe Patreon!"
url = "https://www.patreon.com/bePatron?u=10637849"
weight = 110

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
