author = "Claudiu"
baseurl = "/"
canonifyurls = true
languageCode = "ro"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 12
theme = "alageek"
title = "parsec.ro"
toc = true
DefaultContentLanguage = "ro"
googleAnalytics = "UA-19421559-1"

[params]
copyright = "©2009-2020 parsec.ro | un site de Claudiu Tănăselia."
copyrightUrl = "https://www.parsec.ro"
faviconfile = "/img/favicon.ico"
latestpostcount = 8
logofile2= "/img/logo_large.png"
logofile = "/img/logo.png"
highlightjs = false
progressively = true
facebook = "parsec.ro"
twitter = "superparsec"
email = "contact@parsec.ro"

[[params.best_posts]]
title = "Informații, astronauți și vehicule andocate"
url = "/iss/intro/"

[[params.best_posts]]
title = "Module componente ale ISS"
url = "/iss/module/"

[[params.best_posts]]
title = "Jurnal de activități"
url = "/iss/jurnal/"

[[params.best_posts]]
title = "Echipaje CC-Dev (draft)"
url = "/iss/ccdev/"

[[params.best_posts]]
title = "Oportunități de observație (Heavens Above)"
url = "https://www.heavens-above.com/PassSummary.aspx?satid=25544&lat=46.7712&lng=23.6236&loc=Cluj-Napoca&alt=0&tz=EET"

[[menu.primary]]
identifier = "bul"
name = "Buletin cosmic"
url = "/bul/"
weight = 10

[[menu.primary]]
identifier = "FAQ"
name = "FAQ"
url = "/faq/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "Despre site"
url = "/about/"
weight = 30

[[menu.secondary]]
identifier = "patreon"
name = "Donează prin Patreon"
url = "https://www.patreon.com/superparsec"
weight = 110
