author = "Claudiu"
baseurl = "/"
canonifyurls = true
languageCode = "ro"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 12
theme = "alageek"
title = "parsec.ro"
toc = true
DefaultContentLanguage = "ro"
googleAnalytics = "UA-19421559-1"
fractions = false

[params]
copyright = "©2009-2020 parsec.ro | un site de Claudiu Tănăselia."
copyrightUrl = "https://www.parsec.ro"
faviconfile = "/img/favicon.ico"
latestpostcount = 8
logofile2= "/img/logo_large2.png"
logofile = "/img/logo2.png"
highlightjs = false
progressively = true
facebook = "parsec.ro"
twitter = "superparsec"
email = "contact@parsec.ro"

[[menu.primary]]
identifier = "bul"
name = "Buletine cosmice"
url = "/bul/"
weight = 10

[[menu.primary]]
identifier = "arhiva"
name = "Arhivă"
url = "/arhiva/"
weight = 15

[[menu.primary]]
identifier = "FAQ"
name = "FAQ"
url = "/faq/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "Despre site"
url = "/about/"
weight = 30

[[menu.secondary]]
identifier = "patreon"
name = "Donează prin Patreon"
url = "https://www.patreon.com/superparsec"
weight = 110
