author = "Claudiu"
baseurl = "/"
canonifyurls = true
languageCode = "ro"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
theme = "alageek"
title = "parsec.ro"
toc = true
DefaultContentLanguage = "ro"
googleAnalytics = "UA-19421559-1"

[params]
copyright = "©2009-2019 parsec.ro | un site de Claudiu Tănăselia."
copyrightUrl = "https://www.parsec.ro"
faviconfile = "/img/favicon.ico"
latestpostcount = 5
logofile2= "/img/logo_large.png"
logofile = "/img/logo.png"
highlightjs = false

[[params.best_posts]]
title = "Stația Spațială Internațională"
url = "/iss/intro/"

[[params.best_posts]]
title = "Sonde interplanetare active"
url = "/m/sonde/"

[[params.best_posts]]
title = "Lansări orbitale în 2019"
url = "/r/lansari/"

[[params.best_posts]]
title = "Programul spațial chinezesc"
url = "/p/china/"

[[params.best_posts]]
title = "Programul spațial iranian"
url = "/p/iran/"

[[params.best_posts]]
title = "Programul spațial indian"
url = "/p/india/"

[[params.best_posts]]
title = "Naveta secretă X-37B"
url = "/m/x37b/"

[[params.best_posts]]
title = "Naveta sovietică Buran"
url = "/m/buran/"

[[menu.primary]]
identifier = "bul"
name = "Buletin cosmic"
url = "/bul/"
weight = 10

[[menu.primary]]
identifier = "FAQ"
name = "FAQ"
url = "/faq/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "Despre site"
url = "/about/"
weight = 30

[[menu.secondary]]
identifier = "patreon"
name = "Donează prin Patreon"
url = "https://www.patreon.com/superparsec"
weight = 110

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
